version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
      - image: postgres:9.6
        environment:
          POSTGRES_USER: utility_belt
          POSTGRES_PASSWORD: password
          POSTGRES_DB: utility_belt_test


    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx2000m
      CIRCLE: "yep"
      PG_USER: utility_belt
      PG_PASSWORD: password
      PG_DB: utility_belt_test
      PG_HOST: localhost
      PG_PORT: 5432

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name:  run tests
          command: |
            ./script/ci-test
